// app/routes/home.tsx
import { Link } from "react-router";
import type { MetaFunction } from "react-router";
import { Topbar } from "~/components/Topbar";
import { Footer } from "~/components/Footer";
import { useBreakpoint } from "~/hooks/useBreakpoint";
import backgroundGreen from "~/assets/backgrounds/grid-green.png";
import logoGreen from "~/assets/logos/ta-green.gif";
import styles from "./home.module.css";

export const meta: MetaFunction = () => [{ title: "TERMINAL ANOMALY" }];

const THEME = { color: "#05ffa1", image: logoGreen };

const LINKS = [
  { to: "/gallery", en: "gallery", jp: "ギャラリー" },
  { to: "/about", en: "about", jp: "約" },
  { to: "/projects", en: "projects", jp: "プロジェクト" },
];

export default function Home() {
  const breakpoint = useBreakpoint();

  return (
    <div className={styles.home} style={{ backgroundImage: `url(${backgroundGreen})` }}>
      <Topbar image={THEME.image} gif="home" color={THEME.color} />
      <div className={breakpoint.mdAndUp ? styles.navRowDesktop : styles.navRowMobile}>
        {LINKS.map((link) => (
          <div key={link.to} className={breakpoint.mdAndUp ? styles.navItemDesktop : styles.navItemMobile}>
            <Link to={link.to} className={styles.glow}>
              <div>{link.en}</div>
              <div>{link.jp}</div>
            </Link>
          </div>
        ))}
      </div>
      <Footer />
    </div>
  );
}

// src/views/Home.vue
<!-- 
TODO:
send message page
Redo about page to match new theme
Add Headway info
Add Super Smash Search info
Add vaporwave page, make album art, list other cool sites, music
-->
<template>
  <v-container fluid fill-height class="home">
    <v-layout wrap text-xs-center justify-center>
      <v-flex xs12>
        <Topbar :inner="false" :image="theme.image" :color="theme.color" />
      </v-flex>
      <v-flex :class="$vuetify.breakpoint.mdAndUp? 'xs2' : 'xs12'">
        <div class="glow">
          <router-link to="/gallery">
            <div class="ma-1">gallery</div>
            <div class="ma-1">ギャラリー</div>
          </router-link>
        </div>
      </v-flex>
      <v-flex :class="$vuetify.breakpoint.mdAndUp? 'xs2' : 'xs12'">
        <div class="glow">
          <router-link to="/about">
            <div class="ma-1">about</div>
            <div class="ma-1">アバウト</div>
          </router-link>
        </div>
      </v-flex>
      <v-flex :class="$vuetify.breakpoint.mdAndUp? 'xs2' : 'xs12'">
        <div class="glow">
          <router-link to="/projects">
            <div class="ma-1">projects</div>
            <div class="ma-1">プロジェクト</div>
          </router-link>
        </div>
        </v-flex>
    </v-layout>
    <Footer />
  </v-container>
</template>

<script>
import Footer from '@/components/Footer.vue'
import Topbar from '@/components/Topbar.vue'

export default {
  title: 'TERMINAL ANOMALY',
  components: { Footer, Topbar },
  data () {
    return {
      theme: { color: '#05ffa1', image: 'ta-green.gif' }
    }
  }
}
</script>

<style scoped>
.home {
  width: 100vw;
  height: 100vh;
  background: url(../assets/backgrounds/grid-green.png);
  background-color: black;
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
  color: white;
}

a {
  color: inherit;
  text-decoration: none;
}

.glow {
  font-size: 17px;
  letter-spacing: .5em;
  font-family: 'OCR-A', 'Courier', monospace;
  transition: all 2s ease;
}

.glow:hover {
  color: #05ffa1;
  text-shadow: 0 0 5px #05ffa1;
}
</style>
